# handlers/admin/states.py
# Состояния для ConversationHandler администратора

ADMIN_MAIN = 0
ADMIN_MANAGE = 1
ADMIN_USERS = 2
ADMIN_REQUESTS = 3
ADMIN_EXPORT = 4
ADMIN_USER_ID = 5
ADMIN_USER_ACTION = 6
ADMIN_ROLE_SELECT = 7
ADMIN_REQUEST_ACTION = 100
ADMIN_OPERATOR_SELECT = 101
ADMIN_REQUEST_REASON = 102
